// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp2urN85-PjVzC_HvFOIRbm2WL8LMAojI',
    appId: '1:853924723033:web:1fc001795ce0149a497448',
    messagingSenderId: '853924723033',
    projectId: 'stock-sira',
    authDomain: 'stock-sira.firebaseapp.com',
    storageBucket: 'stock-sira.firebasestorage.app',
    measurementId: 'G-69S78M28JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDvrWfyt4MNy38Nx1_zijTMgIjy2coudE',
    appId: '1:853924723033:android:bb6ea33e83d06883497448',
    messagingSenderId: '853924723033',
    projectId: 'stock-sira',
    storageBucket: 'stock-sira.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANZw10RzGdFwg85sDDCoyTWvc7oS2CLqE',
    appId: '1:853924723033:ios:b8c72109db57d98e497448',
    messagingSenderId: '853924723033',
    projectId: 'stock-sira',
    storageBucket: 'stock-sira.firebasestorage.app',
    iosBundleId: 'com.example.stockTake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANZw10RzGdFwg85sDDCoyTWvc7oS2CLqE',
    appId: '1:853924723033:ios:b8c72109db57d98e497448',
    messagingSenderId: '853924723033',
    projectId: 'stock-sira',
    storageBucket: 'stock-sira.firebasestorage.app',
    iosBundleId: 'com.example.stockTake',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp2urN85-PjVzC_HvFOIRbm2WL8LMAojI',
    appId: '1:853924723033:web:f534eeb545a1ddbb497448',
    messagingSenderId: '853924723033',
    projectId: 'stock-sira',
    authDomain: 'stock-sira.firebaseapp.com',
    storageBucket: 'stock-sira.firebasestorage.app',
    measurementId: 'G-MLBZ39XJ0T',
  );
}
